allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-driver-truenas-volumes
  namespace: kube-system
parameters:
  csi.storage.k8s.io/controller-expand-secret-name: csi-driver-truenas-volumes
  csi.storage.k8s.io/controller-expand-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: csi-driver-truenas-volumes
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
  csi.storage.k8s.io/provisioner-secret-name: csi-driver-truenas-volumes
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
provisioner: truenas.csi.choffmeister.de
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-driver-truenas-csi-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-driver-truenas-csi-controller
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - csi.storage.k8s.io
  resources:
  - csinodeinfos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - csinodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments/status
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - get
  - list
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotcontents
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-driver-truenas-csi-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-driver-truenas-csi-controller
subjects:
- kind: ServiceAccount
  name: csi-driver-truenas-csi-controller
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: csi-driver-truenas-volumes
  namespace: kube-system
stringData:
  iscsi-base-iqn: iqn.2005-10.org.freenas.ctl
  iscsi-initiator-id: "1"
  iscsi-portal-id: "1"
  iscsi-portal-ip: 10.10.10.10
  iscsi-portal-port: "3260"
  truenas-api-key: 1-super-secret-api-key
  truenas-parent-dataset: tank/k8s
  truenas-tls-skip-verify: "true"
  truenas-url: https://10.10.10.10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-driver-truenas-csi
  name: csi-driver-truenas-csi-controller-metrics
  namespace: kube-system
spec:
  ports:
  - name: metrics
    port: 9189
    targetPort: metrics
  selector:
    app: csi-driver-truenas-csi-controller
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-driver-truenas-csi
  name: csi-driver-truenas-csi-node-metrics
  namespace: kube-system
spec:
  ports:
  - name: metrics
    port: 9189
    targetPort: metrics
  selector:
    app: csi-driver-truenas-csi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-driver-truenas-csi-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-driver-truenas-csi-controller
  template:
    metadata:
      labels:
        app: csi-driver-truenas-csi-controller
    spec:
      containers:
      - image: k8s.gcr.io/sig-storage/csi-attacher:v3.2.1
        name: csi-attacher
        volumeMounts:
        - mountPath: /run/csi
          name: socket-dir
      - image: k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
        name: csi-resizer
        volumeMounts:
        - mountPath: /run/csi
          name: socket-dir
      - args:
        - --feature-gates=Topology=true
        - --default-fstype=ext4
        image: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
        name: csi-provisioner
        volumeMounts:
        - mountPath: /run/csi
          name: socket-dir
      - args:
        - -v
        - controller
        env:
        - name: CSI_ENDPOINT
          value: unix:///run/csi/socket
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: ghcr.io/choffmeister/csi-driver-truenas:{{ version }}
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          periodSeconds: 2
          timeoutSeconds: 3
        name: csi-driver-truenas-csi-driver
        ports:
        - containerPort: 9189
          name: metrics
        - containerPort: 9808
          name: healthz
          protocol: TCP
        volumeMounts:
        - mountPath: /run/csi
          name: socket-dir
      - image: k8s.gcr.io/sig-storage/livenessprobe:v2.3.0
        imagePullPolicy: Always
        name: liveness-probe
        volumeMounts:
        - mountPath: /run/csi
          name: socket-dir
      serviceAccountName: csi-driver-truenas-csi-controller
      volumes:
      - emptyDir: {}
        name: socket-dir
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: csi-driver-truenas-csi
  name: csi-driver-truenas-csi-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-driver-truenas-csi
  template:
    metadata:
      labels:
        app: csi-driver-truenas-csi
    spec:
      containers:
      - args:
        - --kubelet-registration-path=/var/lib/kubelet/plugins/truenas.csi.choffmeister.de/socket
        image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0
        name: csi-node-driver-registrar
        volumeMounts:
        - mountPath: /run/csi
          name: plugin-dir
        - mountPath: /registration
          name: registration-dir
      - args:
        - -v
        - node
        env:
        - name: CSI_ENDPOINT
          value: unix:///run/csi/socket
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: ghcr.io/choffmeister/csi-driver-truenas:{{ version }}
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          periodSeconds: 2
          timeoutSeconds: 3
        name: csi-driver-truenas-csi-driver
        ports:
        - containerPort: 9189
          name: metrics
        - containerPort: 9808
          name: healthz
          protocol: TCP
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/kubelet
          mountPropagation: Bidirectional
          name: kubelet-dir
        - mountPath: /run/csi
          name: plugin-dir
        - mountPath: /dev
          name: device-dir
        - mountPath: /host
          name: host-root
      - image: k8s.gcr.io/sig-storage/livenessprobe:v2.3.0
        imagePullPolicy: Always
        name: liveness-probe
        volumeMounts:
        - mountPath: /run/csi
          name: plugin-dir
      hostNetwork: true
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - hostPath:
          path: /var/lib/kubelet
          type: Directory
        name: kubelet-dir
      - hostPath:
          path: /var/lib/kubelet/plugins/truenas.csi.choffmeister.de
          type: DirectoryOrCreate
        name: plugin-dir
      - hostPath:
          path: /var/lib/kubelet/plugins_registry
          type: Directory
        name: registration-dir
      - hostPath:
          path: /dev
          type: Directory
        name: device-dir
      - hostPath:
          path: /
          type: Directory
        name: host-root
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: truenas.csi.choffmeister.de
spec:
  attachRequired: true
  podInfoOnMount: true
  volumeLifecycleModes:
  - Persistent
